### ISSUE TITLE
remove graphql workaround

### ISSUE THREAD

**Issue by thebridsk** [thebridsk/bridgescorer#449]
graphiql has been temporarily disabled because of the publishing of unit test code by graphiql.  This causes build failures looking for npm module 'fs'.

To enable graphiql:
- BldDependencies.scala - add graphiql npm dependency back in
- GraphiQL.scala - in apply method bring back component call. 

see https://github.com/graphql/graphiql/issues/1055 for graphiql cleanup

**Comment by acao** [comment]
it will still look for `fs` without the unit tests

issue is resolved. see:
https://codesandbox.io/s/graphiql-example-nhzvc
